# Generated by Django 6.1 on 2026-08-17 20:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0020_trip_per_user_discount_amount_and_more'),
        ('trips', '0020_trips_average_rating_trips_reviews_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed amount')], default='percentage', max_length=10, verbose_name='discount type')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='discount value')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='maximum discount')),
                ('min_booking_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='minimum booking amount')),
                ('valid_from', models.DateTimeField(verbose_name='valid from')),
                ('valid_until', models.DateTimeField(verbose_name='valid until')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited.', null=True, verbose_name='total usage limit')),
                ('usage_limit_per_user', models.PositiveIntegerField(default=1, verbose_name='usage limit per user')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='times used')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('applicable_trips', models.ManyToManyField(blank=True, related_name='promo_codes', to='trips.trips', verbose_name='applicable trips')),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'ordering': ['-valid_until'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='discount amount')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='used at')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to='profiles.trip_per_user', verbose_name='booking')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='promotions.promocode', verbose_name='promo code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Promo Code Usage',
                'verbose_name_plural': 'Promo Code Usages',
                'ordering': ['-used_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'percentage'), _negated=True), models.Q(('discount_value__gte', 1), ('discount_value__lte', 100)), _connector='OR'), name='promo_percentage_between_1_and_100'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__gt', models.F('valid_from'))), name='promo_valid_until_after_valid_from'),
        ),
        migrations.AddConstraint(
            model_name='promocodeusage',
            constraint=models.UniqueConstraint(fields=('promo_code', 'booking'), name='unique_promo_use_per_booking'),
        ),
    ]
