# Generated by Django 4.2.6 on 2024-08-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_trip_per_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Trip_per_user',
        ),
    ]
