# Generated by Django 4.2.6 on 2024-08-05 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_id_alter_profile_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip_per_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(blank=True, max_length=255, null=True)),
                ('trip_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('username', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='username')),
            ],
        ),
    ]
