# Generated by Django 4.2.6 on 2024-08-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_trip_per_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['username'], 'verbose_name': 'Profiles'},
        ),
    ]
