# Generated by Django 4.2.6 on 2024-08-11 22:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profile_joined_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
