# Generated by Django 4.2.6 on 2024-08-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_profile_joined_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='joined_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
