# Generated by Django 5.0.3 on 2024-08-13 21:03

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_profile_joined_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='A:\\Courses\\React\\myreact\\public'), upload_to='images/users/'),
        ),
    ]
