# Generated by Django 6.1 on 2026-08-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_profile_options_alter_trip_per_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_per_user',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='Paid / completed'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/users/'),
        ),
    ]
