# Generated by Django 6.1 on 2026-08-17 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_hotels_average_rating_hotels_reviews_count_and_more'),
        ('profiles', '0015_trip_per_user_is_paid_alter_profile_photo'),
        ('trips', '0020_trips_average_rating_trips_reviews_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_per_user',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hotels.hotels', verbose_name='hotel'),
        ),
        migrations.AddField(
            model_name='trip_per_user',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='trips.trips', verbose_name='trip'),
        ),
    ]
