# Generated by Django 6.1 on 2026-08-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_resolve_booking_link_orphans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip_per_user',
            name='hotel_name',
        ),
        migrations.RemoveField(
            model_name='trip_per_user',
            name='trip_name',
        ),
    ]
