# Generated by Django 6.1 on 2026-08-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_remove_trip_per_user_hotel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_per_user',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='discount applied'),
        ),
        migrations.AddField(
            model_name='trip_per_user',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='price before discount'),
        ),
    ]
