# Generated by Django 6.1 on 2026-08-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_trip_per_user_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_per_user',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='cancellation reason'),
        ),
        migrations.AddField(
            model_name='trip_per_user',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cancelled at'),
        ),
        migrations.AddField(
            model_name='trip_per_user',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='refund amount'),
        ),
        migrations.AddField(
            model_name='trip_per_user',
            name='refund_status',
            field=models.CharField(choices=[('not_applicable', 'Not applicable'), ('pending', 'Pending'), ('completed', 'Completed')], default='not_applicable', max_length=15, verbose_name='refund status'),
        ),
        migrations.AddField(
            model_name='trip_per_user',
            name='seats',
            field=models.PositiveIntegerField(default=1, verbose_name='travellers'),
        ),
        migrations.AddField(
            model_name='trip_per_user',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=10, verbose_name='status'),
        ),
    ]
