# Generated by Django 6.1 on 2026-08-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_trip_per_user_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('partner', 'Partner'), ('admin', 'Admin')], default='customer', max_length=10, verbose_name='role'),
        ),
    ]
