# Generated by Django 6.1 on 2026-08-18 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255, verbose_name='business name')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='contact phone')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('partner_type', models.CharField(choices=[('hotel_manager', 'Hotel manager'), ('tour_operator', 'Tour operator')], default='tour_operator', max_length=20, verbose_name='partner type')),
                ('is_approved', models.BooleanField(default=False, verbose_name='approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['-created_at'],
            },
        ),
    ]
