# Generated by Django 4.2.6 on 2024-08-08 18:55

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip_features', '0002_remove_trip_features_air_conditioning1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('trip_name', models.OneToOneField(max_length=255, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trip_features.trip_features')),
                ('h_photo1', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve/hotels', verbose_name='hotel photo 1')),
                ('h_photo2', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve/hotels', verbose_name='hotel photo 2')),
                ('h_photo3', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve/hotels', verbose_name='hotel photo 3')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='price per night')),
                ('rate', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True, verbose_name='rate')),
                ('wifi', models.BooleanField(default=False, verbose_name='wifi')),
                ('pool', models.BooleanField(default=False, verbose_name='Swimming pool')),
                ('restaurant', models.BooleanField(default=False, verbose_name='restaurant')),
                ('car_parking', models.BooleanField(default=False, verbose_name='Car Parking ')),
                ('air_conditioning', models.BooleanField(default=False, verbose_name='Air Conditioning')),
                ('room_services', models.BooleanField(default=False, verbose_name='Room Services ')),
                ('beachfront', models.BooleanField(default=False, verbose_name='Beachfront')),
                ('gym', models.BooleanField(default=False, verbose_name='Gym')),
                ('cinema', models.BooleanField(default=False, verbose_name='Cinema')),
            ],
        ),
    ]
