# Generated by Django 4.2.6 on 2024-08-08 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_features', '0002_remove_trip_features_air_conditioning1_and_more'),
        ('hotels', '0002_hotels_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='name',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='hotel name :'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='trip_name',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='trip_features.trip_features', verbose_name='trip name'),
        ),
    ]
