# Generated by Django 4.2.6 on 2024-08-08 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotels_name_alter_hotels_trip_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='trip_name',
        ),
    ]
