# Generated by Django 4.2.6 on 2024-08-08 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_features', '0003_remove_trip_features_id_alter_trip_features_name'),
        ('hotels', '0004_remove_hotels_trip_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='trip_name',
            field=models.ForeignKey(default='Abu Dhabi', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='trip_features.trip_features', verbose_name='trip name'),
            preserve_default=False,
        ),
    ]
