# Generated by Django 4.2.6 on 2024-08-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_hotels_trip_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotels',
            options={'ordering': ['name'], 'verbose_name': 'Hotels'},
        ),
    ]
