# Generated by Django 5.0.3 on 2024-08-13 21:03

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_alter_hotels_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='h_photo1',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='A:\\Courses\\React\\myreact\\public'), upload_to='images/reserve/hotels', verbose_name='hotel photo 1'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='h_photo2',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='A:\\Courses\\React\\myreact\\public'), upload_to='images/reserve/hotels', verbose_name='hotel photo 2'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='h_photo3',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='A:\\Courses\\React\\myreact\\public'), upload_to='images/reserve/hotels', verbose_name='hotel photo 3'),
        ),
    ]
