# Generated by Django 6.1 on 2026-08-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_alter_hotels_h_photo1_alter_hotels_h_photo2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotels',
            options={'ordering': ['name'], 'verbose_name': 'Hotel', 'verbose_name_plural': 'Hotels'},
        ),
    ]
