# Generated by Django 6.1 on 2026-08-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_alter_hotels_options_alter_hotels_h_photo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=3, verbose_name='Average review rating'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Number of reviews'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='h_photo1',
            field=models.ImageField(blank=True, null=True, upload_to='images/reserve/hotels', verbose_name='hotel photo 1'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='h_photo2',
            field=models.ImageField(blank=True, null=True, upload_to='images/reserve/hotels', verbose_name='hotel photo 2'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='h_photo3',
            field=models.ImageField(blank=True, null=True, upload_to='images/reserve/hotels', verbose_name='hotel photo 3'),
        ),
    ]
