# Generated by Django 6.1 on 2026-08-18 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_hotels_average_rating_hotels_reviews_count_and_more'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='partners.partner', verbose_name='owning partner'),
        ),
    ]
