# Generated by Django 6.1 on 2026-08-17 17:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0009_hotels_average_rating_hotels_reviews_count_and_more'),
        ('profiles', '0015_trip_per_user_is_paid_alter_profile_photo'),
        ('trips', '0020_trips_average_rating_trips_reviews_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('comment', models.TextField(blank=True, max_length=1000, verbose_name='comment')),
                ('is_approved', models.BooleanField(default=True, verbose_name='approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='profiles.trip_per_user', verbose_name='booking')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotels.hotels', verbose_name='hotel')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trips.trips', verbose_name='trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('hotel__isnull', True), ('trip__isnull', False)), models.Q(('hotel__isnull', False), ('trip__isnull', True)), _connector='OR'), name='review_target_is_exactly_one_of_trip_or_hotel'), models.UniqueConstraint(fields=('user', 'booking'), name='unique_review_per_user_and_booking')],
            },
        ),
    ]
