# Generated by Django 6.1 on 2026-08-17 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_hotels_average_rating_hotels_reviews_count_and_more'),
        ('profiles', '0015_trip_per_user_is_paid_alter_profile_photo'),
        ('reviews', '0001_initial'),
        ('trips', '0020_trips_average_rating_trips_reviews_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review_per_user_and_booking',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('trip__isnull', False)), fields=('user', 'booking', 'trip'), name='unique_trip_review_per_user_and_booking'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('hotel__isnull', False)), fields=('user', 'booking', 'hotel'), name='unique_hotel_review_per_user_and_booking'),
        ),
    ]
