# Generated by Django 4.2.6 on 2024-08-08 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_delete_trip_features'),
        ('trip_features', '0002_remove_trip_features_air_conditioning1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip_features',
            name='id',
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trips.trips', verbose_name='name'),
        ),
    ]
