# Generated by Django 4.2.6 on 2024-08-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_features', '0003_remove_trip_features_id_alter_trip_features_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip_features',
            options={'ordering': ['name'], 'verbose_name': 'Trip Features'},
        ),
    ]
