# Generated by Django 4.2.6 on 2024-08-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_features', '0004_alter_trip_features_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_features',
            name='bus_start_at_1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='bus_start_at_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='bus_start_at_3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='bus_start_at_4',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='bus_start_at_5',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='plane_start_at_1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='plane_start_at_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='plane_start_at_3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='plane_start_at_4',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='plane_start_at_5',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
