# Generated by Django 5.0.3 on 2024-08-13 21:03

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_features', '0005_trip_features_bus_start_at_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_features',
            name='img1',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='A:\\Courses\\React\\myreact\\public'), upload_to='images/reserve', verbose_name='Trip photo 1'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='img2',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='A:\\Courses\\React\\myreact\\public'), upload_to='images/reserve', verbose_name='Trip photo 2'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='img3',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='A:\\Courses\\React\\myreact\\public'), upload_to='images/reserve', verbose_name='Trip photo 3'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='img4',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='A:\\Courses\\React\\myreact\\public'), upload_to='images/reserve', verbose_name='Trip photo 4'),
        ),
    ]
