# Generated by Django 6.1 on 2026-08-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_features', '0006_alter_trip_features_img1_alter_trip_features_img2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip_features',
            options={'ordering': ['name'], 'verbose_name': 'Trip Features', 'verbose_name_plural': 'Trip Features'},
        ),
    ]
