# Generated by Django 6.1 on 2026-08-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_features', '0007_alter_trip_features_options_alter_trip_features_img1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_features',
            name='img1',
            field=models.ImageField(upload_to='images/reserve', verbose_name='Trip photo 1'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='img2',
            field=models.ImageField(upload_to='images/reserve', verbose_name='Trip photo 2'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='img3',
            field=models.ImageField(upload_to='images/reserve', verbose_name='Trip photo 3'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='img4',
            field=models.ImageField(upload_to='images/reserve', verbose_name='Trip photo 4'),
        ),
    ]
