# Generated by Django 5.0.3 on 2024-04-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('name', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=0, max_digits=5)),
                ('rate', models.DecimalField(decimal_places=0, max_digits=1)),
                ('num', models.DecimalField(decimal_places=0, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=0, max_digits=2)),
                ('desc', models.TextField()),
            ],
        ),
    ]
