# Generated by Django 5.0.3 on 2024-04-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trips',
            options={'ordering': ['Name'], 'verbose_name': 'Trip'},
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='discount',
            new_name='Discount',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='place',
            new_name='Place',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='rate',
            new_name='Rate',
        ),
        migrations.AddField(
            model_name='trips',
            name='Available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='Type',
            field=models.CharField(choices=[('Beach', 'Beach'), ('Nature', 'Nature'), ('City', 'City')], default='Null', max_length=6),
        ),
        migrations.AlterField(
            model_name='trips',
            name='desc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='img',
            field=models.ImageField(upload_to='photos/%y/%m/%d', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='num',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Number of Tourist'),
        ),
    ]
