# Generated by Django 5.0.3 on 2024-04-09 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trips_options_rename_discount_trips_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Photo'),
        ),
        migrations.CreateModel(
            name='TripImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Photo')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trips.trips')),
            ],
        ),
    ]
