# Generated by Django 5.0.3 on 2024-04-12 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trips_img_tripimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripImage',
        ),
    ]
