# Generated by Django 4.2.6 on 2024-04-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_delete_tripimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trips',
            options={'ordering': ['Type'], 'verbose_name': 'Trip'},
        ),
        migrations.AlterField(
            model_name='trips',
            name='img',
            field=models.ImageField(upload_to='images/', verbose_name='Photo'),
        ),
    ]
