# Generated by Django 4.2.6 on 2024-04-17 17:52

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_alter_trips_options_alter_trips_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trips',
            options={'ordering': ['type'], 'verbose_name': 'Trip'},
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='Available',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='Discount',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='Place',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='Rate',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='Type',
        ),
        migrations.AlterField(
            model_name='trips',
            name='img',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='trips',
            name='type',
            field=models.CharField(choices=[('beach', 'beach'), ('nature', 'nature'), ('city', 'city')], default='Null', max_length=6),
        ),
    ]
