# Generated by Django 4.2.6 on 2024-04-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_trips_options_rename_available_trips_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='type',
            field=models.CharField(choices=[('beach', 'beach'), ('nature', 'nature'), ('city', 'city')], default='beach', max_length=6),
        ),
    ]
