# Generated by Django 4.2.6 on 2024-05-15 23:56

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_alter_trips_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip_features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('img1', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='Trip photo 1')),
                ('img2', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='Trip photo 2')),
                ('img3', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='Trip photo 3')),
                ('img4', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='Trip photo 4')),
                ('hotel1', models.BooleanField(default=False, verbose_name='--------------- Hotel 1')),
                ('hotel1_img1', models.ImageField(default='none', storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='hotel 1 photo 1')),
                ('hotel1_img2', models.ImageField(default='none', storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='hotel 1 photo 2')),
                ('hotel1_img3', models.ImageField(default='none', storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='hotel 1 photo 3')),
                ('price1', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='price per night')),
                ('rate1', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='rate')),
                ('wifi1', models.BooleanField(default=False, verbose_name='wifi')),
                ('pool1', models.BooleanField(default=False, verbose_name='pool')),
                ('restaurant1', models.BooleanField(default=False, verbose_name='restaurant')),
                ('hotel2', models.BooleanField(default=False, verbose_name='--------------- Hotel 2')),
                ('hotel2_img1', models.ImageField(default='none', storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='hotel 2 photo 1')),
                ('hotel2_img2', models.ImageField(default='none', storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='hotel 2 photo 2')),
                ('hotel2_img3', models.ImageField(default='none', storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='hotel 2 photo 3')),
                ('price2', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='price per night')),
                ('rate2', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='rate')),
                ('wifi2', models.BooleanField(default=False, verbose_name='wifi')),
                ('pool2', models.BooleanField(default=False, verbose_name='pool')),
                ('restaurant2', models.BooleanField(default=False, verbose_name='restaurant')),
                ('hotel3', models.BooleanField(default=False, verbose_name='--------------- Hotel 3')),
                ('hotel3_img1', models.ImageField(default='none', storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='hotel 3 photo 1')),
                ('hotel3_img2', models.ImageField(default='none', storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='hotel 3 photo 2')),
                ('hotel3_img3', models.ImageField(default='none', storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='hotel 3 photo 3')),
                ('price3', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='price per night')),
                ('rate3', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='rate')),
                ('wifi3', models.BooleanField(default=False, verbose_name='wifi')),
                ('pool3', models.BooleanField(default=False, verbose_name='pool')),
                ('restaurant3', models.BooleanField(default=False, verbose_name='restaurant')),
                ('hotel4', models.BooleanField(default=False, verbose_name='--------------- Hotel 4')),
                ('hotel4_img1', models.ImageField(default='none', storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='hotel 4 photo 1')),
                ('hotel4_img2', models.ImageField(default='none', storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='hotel 4 photo 2')),
                ('hotel4_img3', models.ImageField(default='none', storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='hotel 4 photo 3')),
                ('price4', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='price per night')),
                ('rate4', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='rate')),
                ('wifi4', models.BooleanField(default=False, verbose_name='wifi')),
                ('pool4', models.BooleanField(default=False, verbose_name='pool')),
                ('restaurant4', models.BooleanField(default=False, verbose_name='restaurant')),
            ],
        ),
        migrations.AlterField(
            model_name='trips',
            name='img',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/', verbose_name='Trip photo'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='rate',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='trips',
            name='type',
            field=models.CharField(choices=[('Beach', 'Beach'), ('Nature', 'Nature'), ('City', 'City')], default='Beach', max_length=6),
        ),
    ]
