# Generated by Django 4.2.6 on 2024-05-18 14:24

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_trip_features_alter_trips_img_alter_trips_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_features',
            name='access_bus_1',
            field=models.BooleanField(default=False, verbose_name=' access point 1 by bus'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_bus_2',
            field=models.BooleanField(default=False, verbose_name=' access point 2 by bus'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_bus_3',
            field=models.BooleanField(default=False, verbose_name=' access point 3 by bus'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_bus_4',
            field=models.BooleanField(default=False, verbose_name=' access point 4 by bus'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_bus_5',
            field=models.BooleanField(default=False, verbose_name=' access point 5 by bus'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_bus_name_1',
            field=models.CharField(blank=True, default='none', max_length=150, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_bus_name_2',
            field=models.CharField(blank=True, default='none', max_length=150, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_bus_name_3',
            field=models.CharField(blank=True, default='none', max_length=150, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_bus_name_4',
            field=models.CharField(blank=True, default='none', max_length=150, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_bus_name_5',
            field=models.CharField(blank=True, default='none', max_length=150, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_bus_price_1',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_bus_price_2',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_bus_price_3',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_bus_price_4',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_bus_price_5',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_plane_1',
            field=models.BooleanField(default=False, verbose_name=' access point 1 by plane'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_plane_2',
            field=models.BooleanField(default=False, verbose_name=' access point 2 by plane'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_plane_3',
            field=models.BooleanField(default=False, verbose_name=' access point 3 by plane'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_plane_4',
            field=models.BooleanField(default=False, verbose_name=' access point 4 by plane'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_plane_5',
            field=models.BooleanField(default=False, verbose_name=' access point 5 by plane'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_plane_name_1',
            field=models.CharField(blank=True, default='none', max_length=150, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_plane_name_2',
            field=models.CharField(blank=True, default='none', max_length=150, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_plane_name_3',
            field=models.CharField(blank=True, default='none', max_length=150, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_plane_name_4',
            field=models.CharField(blank=True, default='none', max_length=150, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_plane_name_5',
            field=models.CharField(blank=True, default='none', max_length=150, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_plane_price_1',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_plane_price_2',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_plane_price_3',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_plane_price_4',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='access_plane_price_5',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='hotel1_img1',
            field=models.ImageField(blank=True, default='none', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='hotel 1 photo 1'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='hotel1_img2',
            field=models.ImageField(blank=True, default='none', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='hotel 1 photo 2'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='hotel1_img3',
            field=models.ImageField(blank=True, default='none', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='hotel 1 photo 3'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='hotel2_img1',
            field=models.ImageField(blank=True, default='none', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='hotel 2 photo 1'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='hotel2_img2',
            field=models.ImageField(blank=True, default='none', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='hotel 2 photo 2'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='hotel2_img3',
            field=models.ImageField(blank=True, default='none', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='hotel 2 photo 3'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='hotel3_img1',
            field=models.ImageField(blank=True, default='none', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='hotel 3 photo 1'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='hotel3_img2',
            field=models.ImageField(blank=True, default='none', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='hotel 3 photo 2'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='hotel3_img3',
            field=models.ImageField(blank=True, default='none', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='hotel 3 photo 3'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='hotel4_img1',
            field=models.ImageField(blank=True, default='none', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='hotel 4 photo 1'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='hotel4_img2',
            field=models.ImageField(blank=True, default='none', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='hotel 4 photo 2'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='hotel4_img3',
            field=models.ImageField(blank=True, default='none', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='hotel 4 photo 3'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='price1',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True, verbose_name='price per night'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True, verbose_name='price per night'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='price3',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True, verbose_name='price per night'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='price4',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True, verbose_name='price per night'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='rate1',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='enter rate', max_digits=2, null=True, verbose_name='rate'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='rate2',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True, verbose_name='rate'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='rate3',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True, verbose_name='rate'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='rate4',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True, verbose_name='rate'),
        ),
    ]
