# Generated by Django 4.2.6 on 2024-05-18 14:32

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_trip_features_access_bus_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_features',
            name='hotel1_img1',
            field=models.ImageField(blank=True, default='none', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve/hotels', verbose_name='hotel 1 photo 1'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='hotel1_img2',
            field=models.ImageField(blank=True, default='none', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve/hotels', verbose_name='hotel 1 photo 2'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='hotel1_img3',
            field=models.ImageField(blank=True, default='none', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve/hotels', verbose_name='hotel 1 photo 3'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='hotel2_img1',
            field=models.ImageField(blank=True, default='none', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve/hotels', verbose_name='hotel 2 photo 1'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='hotel2_img2',
            field=models.ImageField(blank=True, default='none', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve/hotels', verbose_name='hotel 2 photo 2'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='hotel2_img3',
            field=models.ImageField(blank=True, default='none', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve/hotels', verbose_name='hotel 2 photo 3'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='hotel3_img1',
            field=models.ImageField(blank=True, default='none', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve/hotels', verbose_name='hotel 3 photo 1'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='hotel3_img2',
            field=models.ImageField(blank=True, default='none', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve/hotels', verbose_name='hotel 3 photo 2'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='hotel3_img3',
            field=models.ImageField(blank=True, default='none', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve/hotels', verbose_name='hotel 3 photo 3'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='hotel4_img1',
            field=models.ImageField(blank=True, default='none', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve/hotels', verbose_name='hotel 4 photo 1'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='hotel4_img2',
            field=models.ImageField(blank=True, default='none', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve/hotels', verbose_name='hotel 4 photo 2'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='hotel4_img3',
            field=models.ImageField(blank=True, default='none', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve/hotels', verbose_name='hotel 4 photo 3'),
        ),
    ]
