# Generated by Django 4.2.6 on 2024-05-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_alter_trip_features_hotel1_img1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_features',
            name='hotel1_name',
            field=models.CharField(blank=True, default='none', max_length=150, null=True, verbose_name='hotel name :'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='hotel2_name',
            field=models.CharField(blank=True, default='none', max_length=150, null=True, verbose_name='hotel name :'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='hotel3_name',
            field=models.CharField(blank=True, default='none', max_length=150, null=True, verbose_name='hotel name :'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='hotel4_name',
            field=models.CharField(blank=True, default='none', max_length=150, null=True, verbose_name='hotel name :'),
        ),
    ]
