# Generated by Django 4.2.6 on 2024-07-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_trip_features_hotel1_name_trip_features_hotel2_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_features',
            name='air_conditioning1',
            field=models.BooleanField(default=False, verbose_name='Air Conditioning'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='air_conditioning2',
            field=models.BooleanField(default=False, verbose_name='Air Conditioning'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='air_conditioning3',
            field=models.BooleanField(default=False, verbose_name='Air Conditioning'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='air_conditioning4',
            field=models.BooleanField(default=False, verbose_name='Air Conditioning'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='beachfront1',
            field=models.BooleanField(default=False, verbose_name='Beachfront'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='beachfront2',
            field=models.BooleanField(default=False, verbose_name='Beachfront'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='beachfront3',
            field=models.BooleanField(default=False, verbose_name='Beachfront'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='beachfront4',
            field=models.BooleanField(default=False, verbose_name='Beachfront'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='car_parking1',
            field=models.BooleanField(default=False, verbose_name='Car Parking '),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='car_parking2',
            field=models.BooleanField(default=False, verbose_name='Car Parking '),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='car_parking3',
            field=models.BooleanField(default=False, verbose_name='Car Parking '),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='car_parking4',
            field=models.BooleanField(default=False, verbose_name='Car Parking '),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='cinema1',
            field=models.BooleanField(default=False, verbose_name='Cinema'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='cinema2',
            field=models.BooleanField(default=False, verbose_name='Cinema'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='cinema3',
            field=models.BooleanField(default=False, verbose_name='Cinema'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='cinema4',
            field=models.BooleanField(default=False, verbose_name='Cinema'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='gym1',
            field=models.BooleanField(default=False, verbose_name='Gym'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='gym2',
            field=models.BooleanField(default=False, verbose_name='Gym'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='gym3',
            field=models.BooleanField(default=False, verbose_name='Gym'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='gym4',
            field=models.BooleanField(default=False, verbose_name='Gym'),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='room_services1',
            field=models.BooleanField(default=False, verbose_name='Room Services '),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='room_services2',
            field=models.BooleanField(default=False, verbose_name='Room Services '),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='room_services3',
            field=models.BooleanField(default=False, verbose_name='Room Services '),
        ),
        migrations.AddField(
            model_name='trip_features',
            name='room_services4',
            field=models.BooleanField(default=False, verbose_name='Room Services '),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='pool1',
            field=models.BooleanField(default=False, verbose_name='Swimming pool'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='pool2',
            field=models.BooleanField(default=False, verbose_name='Swimming pool'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='pool3',
            field=models.BooleanField(default=False, verbose_name='Swimming pool'),
        ),
        migrations.AlterField(
            model_name='trip_features',
            name='pool4',
            field=models.BooleanField(default=False, verbose_name='Swimming pool'),
        ),
    ]
