# Generated by Django 4.2.6 on 2024-08-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_trip_features_air_conditioning1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='id',
        ),
        migrations.AlterField(
            model_name='trips',
            name='name',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
