# Generated by Django 4.2.6 on 2024-08-05 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_remove_trips_id_alter_trips_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_features',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trips', verbose_name='name'),
        ),
    ]
