# Generated by Django 4.2.6 on 2024-08-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_alter_trip_features_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip_features',
        ),
    ]
