# Generated by Django 5.0.3 on 2024-08-13 21:03

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_delete_trip_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='img',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='A:\\Courses\\React\\myreact\\public'), upload_to='images/', verbose_name='Trip photo'),
        ),
    ]
