# Generated by Django 5.0.3 on 2024-09-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0017_alter_trips_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='profit',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
