# Generated by Django 5.0.3 on 2024-09-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0018_trips_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='profit',
        ),
    ]
