# Generated by Django 6.1 on 2026-08-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0019_remove_trips_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=3, verbose_name='Average review rating'),
        ),
        migrations.AddField(
            model_name='trips',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Number of reviews'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='img',
            field=models.ImageField(upload_to='images/', verbose_name='Trip photo'),
        ),
    ]
