# Generated by Django 6.1 on 2026-08-18 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0020_trips_average_rating_trips_reviews_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='capacity',
            field=models.PositiveIntegerField(default=30, verbose_name='Seats per departure'),
        ),
        migrations.CreateModel(
            name='TripAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('total_seats', models.PositiveIntegerField(verbose_name='total seats')),
                ('booked_seats', models.PositiveIntegerField(default=0, verbose_name='booked seats')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='trips.trips', verbose_name='trip')),
            ],
            options={
                'verbose_name': 'Trip Availability',
                'verbose_name_plural': 'Trip Availability',
                'ordering': ['trip', 'date'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'date'), name='unique_availability_per_trip_date')],
            },
        ),
    ]
