# Generated by Django 6.1 on 2026-08-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0021_trips_capacity_tripavailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=30, help_text='Leave empty for the default of 30.', verbose_name='Seats per departure'),
        ),
    ]
