# Generated by Django 6.1 on 2026-08-18 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('trips', '0022_alter_trips_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='partners.partner', verbose_name='owning partner'),
        ),
    ]
